### PR TITLE
Batch overwrite

### PR DESCRIPTION
**Pull request by jfennick**
[vina_batch_overwrite.zip](https://github.com/ccsb-scripps/AutoDock-Vina/files/9792761/vina_batch_overwrite.zip)

When using the --batch option with ligands that have the same filename but are in different directories, the output pose *.pdbqt files will all have the same filename and will thus be overwritten. See attached zip file for a minimal reproducible example.

This PR simply prepends 0_, 1_, etc to the output filenames. If you prefer another solution, feel free to implement it and close this PR. I'd just like to get this fixed.

### CODE REVIEW

**Comment by diogomart** [comment]
Thanks for the minimal example, it's very clear. This PR may break scripts that parse the results, as those scripts wouldn't know about the prefix. The solution would be to add the prefix (or suffix) only if the output filename would be repeated. This would guarantee compatibility whenever all ligand base filenames are unique.

**Comment by jfennick** [comment]
I've changed the PR so it only adds suffixes if there is a name conflict. Let me know if there are any other changes you would like.

**Comment by diogomart** [comment]
Thank you @jfennick I'll look into it soon. Would you benefit from a release v1.2.4 or having this merged onto the develop branch suffices for you?

**Comment by jfennick** [comment]
Thanks. A 1.2.4 release would be preferred, both for this issue and due to https://github.com/ccsb-scripps/AutoDock-Vina/pull/81

**Comment by diogomart** [comment]
Thank you @jfennick for this PR.

**Pull request merged**
