### PR TITLE
Windows compilation fixes and Visual Studio project files

### PR DESCRIPTION
**Pull request by atillack**
This PR adds Visual Studio project files to Vina to be able to compile a Windows version. It expects the current Boost 1.77 version installed in `C:\local\boost_1_77_0` (default for the precompiled binary version) for either x86 or x64.

Additionally, some small fixes where needed for VS to successfully link everything (`struct` and `class` were sometimes used interchangeably) and for regular whitespace and "non-traditional whitespace" (`\v`, `\r`) to not spoil reading pdbqt files on Windows (aka "empty" lines).

I tested our examples successfully on Windows and macOS with this version.

### CODE REVIEW

**Comment by talregev** [comment]
Please also add windows to ci. Thank you.

**Comment by talregev** [comment]
Thank you for the windows ci.
I have small suggestion. You can use cmd instead of PowerShell. 
In ci there is windows 10, it have a curl.exe to use there.

**Comment by diogomart** [comment]
Let's delete "forcefield.h" and "forcefield.cpp" because they are not needed :)
Related to #23, #27, and globing "*.h" *".cpp" in https://github.com/microsoft/vcpkg/pull/19645

**Comment by talregev** [comment]
Acceptable solution. Will be from next release.

**Comment by atillack** [comment]
@diogomart Agreed and done.

**Comment by talregev** [comment]
Can you restart windows ci?

**Comment by talregev** [comment]
Thank you.

**Comment by jeeberhardt** [comment]
This PR still needs some work on my side (python wheels for Windows), I am temporarily convert it to draft.

**Comment by talregev** [comment]
My vcpkg PR was merge. Please merge this PR for consistency. 
Thank you.

**Comment by atillack** [comment]
@jeeberhardt Merging - thank you for our quick off-channel talk ;-)

**Pull request merged**
