### PR TITLE
Update installation.rst

### PR DESCRIPTION
**Pull request by rczerminski-valo**
added `mamba install swig` before `pip install vina`

### CODE REVIEW

**Comment by diogomart** [comment]
Thanks for the PR. There's no need for mamba when we already have instructions with conda. It would make sense to have the same instructions as we do in the [pip page](https://pypi.org/project/vina/), which is essentially:

```
conda install -c conda-forge numpy swig boost-cpp sphinx sphinx_rtd_theme
pip install vina
```
If you want, go ahead and replace mamba with the line above in the PR

**Comment by diogomart** [comment]
Thanks!

**Comment by rczerminski-valo** [comment]
Just changed to `conda install -c conda-forge numpy swig boost-cpp sphinx sphinx_rtd_theme`
BTW: `mamba` seems to be significantly faster overall...

**Comment by diogomart** [comment]
That's good to know. I haven't used mamba yet, but will consider it

**Pull request merged**
