### PR TITLE
Add callback to report progress

### PR DESCRIPTION
**Pull request by AenBleidd**
Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by atillack** [comment]
@AenBleidd Thank you for the commit. The implementation looks good to me and we'll start running internal tests soon.

**Review by diogomart — APPROVED** [review]
Looks good to me :-) Tested on linux, both command line and python. No runtime differences observed (as expected).

**Comment by atillack** [comment]
@diogomart Thank you!

**Comment by atillack** [comment]
@AenBleidd I will go ahead and merge this PR. Also FYI, we found a regression related to PR #26 which is fixed in PR #52  that should be merged soon as well.

**Comment by AenBleidd** [comment]
@atillack, thank you for review, merge and update.

**Pull request merged**
